###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

hbwa-mysql:
  image: mysql:5.7
  container_name: hbwa-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=hbwa
    - MYSQL_USER=hbwa
    - MYSQL_PASSWORD=test
  ports:
   - "3306:3306"

hbwa-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: hbwa-php-fpm
  volumes:
    - ..:/var/www/hbwa
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - hbwa-mysql
  environment:
    - MYSQL_DATABASE=hbwa
    - MYSQL_USER=hbwa
    - MYSQL_PASSWORD=test
    - MYSQL_HOST=hbwa-mysql
  ports:
   - "9901:9901"

hbwa-webserver:
  image: phpdockerio/nginx:latest
  container_name: hbwa-webserver
  volumes:
      - ..:/var/www/hbwa
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - hbwa-php-fpm


hbwa-api-server:
  image: phpdockerio/nginx:latest
  container_name: hbwa-api-server
  volumes:
      - ..:/var/www/hbwa
      - ./nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "3333:80"
  links:
   - hbwa-php-fpm